# Generated by Django 3.2.4 on 2021-06-19 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_image_uploaded_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_link',
            new_name='image',
        ),
    ]
