# Generated by Django 3.2.4 on 2021-09-15 15:39

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_image_link_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='classified_as',
            field=models.CharField(choices=[('0', 'reaching behind'), ('1', 'talking on the phone - left'), ('2', 'operating the radio'), ('3', 'talking to passenger'), ('4', 'texting - left'), ('5', 'drinking'), ('6', 'hair and makeup'), ('7', 'texting - right'), ('8', 'talking on the phone - right'), ('9', 'safe driving')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=main.models.update_filename),
        ),
    ]
