# Generated by Django 3.2.4 on 2021-09-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_image_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='classified_as',
            field=models.CharField(choices=[('0', 'drinking'), ('1', 'hair and makeup'), ('2', 'reaching behind'), ('3', 'operating the radio'), ('4', 'safe driving'), ('5', 'talking on the phone - left'), ('6', 'talking on the phone - right'), ('7', 'talking to passenger'), ('8', 'texting - left'), ('9', 'texting - right')], default=None, max_length=1, null=True),
        ),
    ]
