
import turtle
import time
p = 40
turtle.bgcolor('black')
colors = ['red', 'purple', 'blue','gray', 'green', 'orange', 'yellow','teal','orange','white',]
skk = turtle.Pen()
# print(skk.position())
skk.goto(-160,0)
skk.pencolor('blue')

name1 = input('Enter Your Name:')

name = name1.upper()
for i in range(len(name)):
    if name[i] == 'A':  
        # A
        skk.left(70)
        skk.forward(65)
        skk.right(140)
        skk.forward(65)
        skk.penup()
        skk.left(180)
        skk.forward(30)
        skk.left(70)
        skk.pendown()
        skk.forward(23.94)
        skk.penup()
        skk.right(180)
        skk.forward(23.94)
        skk.right(70)
        skk.forward(30)
        skk.left(70)
        skk.pendown()

        skk.pencolor('black')
        skk.forward(15)
        skk.pencolor('blue')
    elif name[i] == 'B':
        #B
        skk.left(90)
        skk.forward(60)
        skk.right(90)
        skk.forward(30)
        skk.right(90)
        skk.forward(25)
        skk.right(80)
        skk.forward(32)
        skk.right(180)
        skk.right(20)
        skk.forward(32)
        skk.right(80)
        skk.forward(25)
        skk.right(90)
        skk.forward(30)
        skk.right(180)
        skk.forward(30)
        skk.pencolor('black')
        skk.forward(15)
        skk.pencolor('blue')
    elif name[i] == 'C':
        #C
        pos=skk.position()
        print(pos)
        skk.left(90)
        skk.forward(60)
        skk.right(90)
        skk.forward(25)
        skk.right(40)
        skk.forward(15)
        skk.pencolor('black')
        skk.goto(pos)
        skk.pencolor('blue')
        skk.left(40)
        skk.forward(25)
        skk.left(40)
        skk.forward(15)
        skk.right(180)
        skk.forward(15)
        skk.left(140)
        skk.pencolor('black')
        skk.forward(30)
        skk.pencolor('blue')
    elif name[i] == 'D':
        #D
        skk.left(90)
        skk.forward(60)
        skk.right(135)
        skk.forward(45)
        skk.right(90)
        skk.forward(45)
        skk.left(135)
        skk.pencolor('black')
        skk.forward(45)
        skk.pencolor('blue')
    elif name[i] == 'E':
        #E
        skk.left(90)
        pos1 = skk.position()
        skk.forward(30)
        pos2 = skk.position()
        skk.forward(30)
        skk.right(90)
        skk.forward(30)
        skk.pencolor('black')
        skk.goto(pos2)
        skk.pencolor('blue')
        skk.forward(25)
        skk.pencolor('black')
        skk.goto(pos1)
        skk.pencolor('blue')
        skk.forward(30)
        skk.pencolor('black')
        skk.forward(15)
        skk.pencolor('blue')
    elif name[i] == 'F':
        #F
        skk.left(90)
        pos1 = skk.position()
        skk.forward(30)
        pos2 = skk.position()
        skk.forward(30)
        skk.right(90)
        skk.forward(30)
        skk.pencolor('black')
        skk.goto(pos2)
        skk.pencolor('blue')
        skk.forward(25)
        skk.pencolor('black')
        skk.goto(pos1)
        skk.forward(45)
        skk.pencolor('blue')
    elif name[i] == 'G':
        # G
        pos1 = skk.position()
        skk.left(90)
        skk.forward(60)
        skk.right(90)
        skk.forward(30)
        skk.right(90)
        skk.forward(20)
        skk.pencolor('black')
        skk.goto(pos1)
        skk.pencolor('blue')
        skk.left(90)
        skk.forward(23)
        skk.left(90)
        skk.forward(10)
        skk.right(90)
        skk.forward(7)
        skk.right(90)
        skk.forward(10)
        skk.left(90)
        skk.pencolor('black')
        skk.forward(15)
        skk.pencolor('blue')
    elif name[i] == 'H':
        # H
        skk.left(90)
        skk.forward(60)
        skk.right(180)
        skk.forward(30)
        skk.left(90)
        skk.forward(30)
        skk.left(90)
        skk.forward(30)
        skk.right(180)
        skk.forward(60)
        skk.left(90)
        skk.pencolor('black')
        skk.forward(15)
        skk.pencolor('blue')
    elif name[i] == 'I':
        # I
        skk.forward(30)
        pos1 = skk.position()
        skk.left(180)
        skk.forward(15)
        skk.right(90)
        skk.forward(60)
        skk.left(90)
        skk.forward(15)
        skk.right(180)
        skk.forward(30)
        skk.pencolor('black')
        skk.goto(pos1)
        skk.forward(15)
        skk.pencolor('blue')
    elif name[i] == 'J':
        # J
        skk.left(90)
        skk.forward(20)
        skk.right(180)
        skk.forward(20)
        skk.left(90)
        skk.forward(15)
        pos1 = skk.position()
        skk.left(90)
        skk.forward(60)
        skk.left(90)
        skk.forward(15)
        skk.right(180)
        skk.forward(30)
        skk.pencolor('black')
        skk.goto(pos1)
        skk.forward(30)
        skk.pencolor('blue')
    elif name[i] == 'K':
        # K
        skk.pencolor('black')
        skk.forward(10)
        skk.pencolor('blue')
        skk.left(90)
        skk.forward(30)
        pos1 = skk.position()
        skk.forward(30)
        skk.goto(pos1)
        skk.right(40)
        skk.forward(42)
        skk.right(180)
        skk.forward(36)
        skk.left(80)
        skk.forward(42)
        skk.left(50)
        skk.pencolor('black')
        skk.forward(15)
        skk.pencolor('blue')
    elif name[i] == 'L':
        # L
        pos1 = skk.position()
        skk.left(90)
        skk.forward(60)
        skk.goto(pos1)
        skk.right(90)
        skk.forward(25)
        skk.pencolor('black')
        skk.forward(15)
        skk.pencolor('blue')
    elif name[i] == 'M':
        # M
        skk.left(90)
        skk.forward(60)
        skk.right(140)
        skk.forward(30)
        skk.left(100)
        skk.forward(30)
        skk.right(140)
        skk.forward(60)
        skk.left(90)
        skk.pencolor('black')
        skk.forward(15)
        skk.pencolor('blue')
    elif name[i] == 'N':
        # N
        skk.left(90)
        skk.forward(60)
        skk.right(150)
        skk.forward(70)
        skk.left(150)
        skk.forward(60)
        skk.right(180)
        skk.forward(60)
        skk.left(90)
        skk.pencolor('black')
        skk.forward(15)
        skk.pencolor('blue')
    elif name[i] == 'O':
        # O
        skk.left(90)
        skk.forward(60)
        skk.right(90)
        skk.forward(30)
        skk.right(90)
        skk.forward(60)
        skk.right(90)
        skk.forward(30)
        skk.right(180)
        skk.forward(30)
        skk.pencolor('black')
        skk.forward(15)
        skk.pencolor('blue')
    elif name[i] == 'P':
        # P
        pos1=skk.position()
        skk.left(90)
        skk.forward(60)
        skk.right(90)
        skk.forward(30)
        skk.right(90)
        skk.forward(30)
        skk.right(90)
        skk.forward(30)
        skk.goto(pos1)
        skk.left(180)
        skk.pencolor('black')
        skk.forward(45)
        skk.pencolor('blue')
    elif name[i] == 'Q':
        # Q
        skk.left(90)
        skk.pencolor('black')
        skk.forward(15)
        skk.pencolor('blue')
        skk.forward(45)
        skk.right(90)
        skk.forward(30)
        skk.right(90)
        skk.forward(45)
        skk.right(90)
        skk.forward(30)
        skk.right(180)
        skk.forward(23)
        skk.right(40)
        skk.forward(20)
        skk.left(40)
        skk.pencolor('black')
        skk.forward(15)
        skk.pencolor('blue')
    elif name[i] == 'R':
        # R
        skk.left(90)
        skk.forward(60)
        skk.right(90)
        skk.forward(30)
        skk.right(90)
        skk.forward(30)
        skk.right(90)
        skk.forward(30)
        skk.left(135)
        skk.forward(45)
        skk.left(45)
        skk.pencolor('black')
        skk.forward(15)
        skk.pencolor('blue')
    elif name[i] == 'S':
        # S
        skk.forward(30)
        pos1 = skk.position()
        skk.left(90)
        skk.forward(30)
        skk.left(90)
        skk.forward(30)
        skk.right(90)
        skk.forward(30)
        skk.right(90)
        skk.forward(30)
        skk.pencolor('black')
        skk.forward(10)
        skk.goto(pos1)
        skk.forward(15)
        skk.pencolor('blue')
    elif name[i] == 'T':
        # T
        skk.pencolor('black')
        skk.forward(15)
        skk.pencolor('blue')
        skk.left(90)
        skk.forward(60)
        skk.left(90)
        skk.forward(15)
        skk.right(180)
        skk.forward(30)
        skk.right(90)
        skk.pencolor('black')
        skk.forward(60)
        skk.left(90)
        skk.forward(15)
        skk.pencolor('blue')
    elif name[i] == 'U':
        # U
        skk.left(90)
        skk.forward(60)
        skk.right(180)
        skk.forward(60)
        skk.left(90)
        skk.forward(30)
        skk.left(90)
        skk.forward(60)
        skk.right(180)
        skk.forward(60)
        skk.pencolor('black')
        skk.left(90)
        skk.forward(15)
        skk.pencolor('blue')
    elif name[i] == 'V':
        #V
        skk.left(90)
        skk.pencolor('black')
        skk.forward(60)
        skk.pencolor('blue')
        skk.right(165)
        skk.forward(62)
        skk.left(150)
        skk.forward(62)
        skk.right(165)
        skk.pencolor('black')
        skk.forward(60)
        skk.left(90)
        skk.forward(15)
        skk.pencolor('blue')
    elif name[i] == 'W':
        # W
        skk.left(90)
        skk.forward(60)
        skk.right(180)
        skk.forward(60)
        skk.left(140)
        skk.forward(30)
        skk.right(100)
        skk.forward(30)
        skk.left(140)
        skk.forward(60)
        skk.left(180)
        skk.forward(60)
        skk.left(90)
        skk.pencolor('black')
        skk.forward(15)
        skk.pencolor('blue')
    elif name[i] == 'X':
        # X
        skk.left(63)
        skk.forward(67)
        skk.left(117)
        skk.pencolor('black')
        skk.forward(30)
        skk.pencolor('blue')
        skk.left(117)
        skk.forward(67)
        skk.left(63)
        skk.pencolor('black')
        skk.forward(15)
        skk.pencolor('blue')
    elif name[i] == 'Y':
        # Y
        skk.left(90)
        skk.pencolor('black')
        skk.forward(60)
        skk.pencolor('blue')
        skk.right(140)
        skk.forward(40)
        skk.left(100)
        skk.forward(40)
        skk.right(180)
        skk.forward(40)
        skk.left(40)
        skk.forward(30)
        skk.left(90)
        skk.pencolor('black')
        skk.forward(45)
        skk.pencolor('blue')
    elif name[i] == 'Z':
        # Z
        skk.left(90)
        skk.pencolor('black')
        skk.forward(60)
        skk.pencolor('blue')
        skk.right(90)
        skk.forward(30)
        skk.right(120)
        skk.forward(70)
        skk.left(120)
        skk.forward(30)
        skk.pencolor('black')
        skk.forward(15)
        skk.pencolor('blue')

turtle.done()